if(location.protocol==='file:')location.replace('http://localhost:3000');
let products = JSON.parse(localStorage.getItem('godown-products')) || [];
let activity = JSON.parse(localStorage.getItem('godown-activity')) || [];
let savedProductCount = products.length;
let pendingCategory = '';
document.querySelector('#product-form').addEventListener('submit',()=>{pendingCategory=document.querySelector('#new-category').value.trim()});
setInterval(()=>{if(products.length>savedProductCount){products[products.length-1].category=products[products.length-1].category||pendingCategory||'Uncategorized';savedProductCount=products.length;save()}},100);
if (products.some(p => ['ALD-04-ANT', 'MH-06-SS', 'TB-08-BLK', 'DH-03-SS', 'ALD-06-GOL', 'CK-32-BRS'].includes(p.code))) {
	products = [];
	activity = [];
	localStorage.removeItem('godown-products');
	localStorage.removeItem('godown-activity');
}
let currentView = 'overview';
let currentRole = sessionStorage.getItem('godown-role');
let serverToken = sessionStorage.getItem('godown-token');
let skipNextStateSync = false;
const apiBase=location.protocol==='file:'?'http://localhost:3000':'';
async function loadServerState(){if(!serverToken)return;try{const response=await fetch(`${apiBase}/api/state`,{headers:{Authorization:`Bearer ${serverToken}`}});if(!response.ok)return;const state=await response.json();products=state.products||[];activity=state.movements||[];localStorage.setItem('godown-products',JSON.stringify(products));localStorage.setItem('godown-activity',JSON.stringify(activity));render()}catch(error){console.warn('Server state unavailable; using local data.',error)}}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const input={role:document.querySelector('#login-role').value,username:document.querySelector('#login-username').value.trim(),password:document.querySelector('#login-password').value};try{const response=await fetch(`${apiBase}/api/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});if(!response.ok)throw new Error('Invalid credentials');const result=await response.json();serverToken=result.token;currentRole=result.role;sessionStorage.setItem('godown-role',currentRole);sessionStorage.setItem('godown-token',serverToken);document.querySelector('#login-screen').classList.add('hidden');await loadServerState();render()}catch(error){document.querySelector('#login-error').textContent='Server login failed. Start the app with npm start.'}},true);
const $ = (q) => document.querySelector(q);
document.querySelector('#movement-form').addEventListener('submit',()=>setTimeout(()=>{const entry=activity[0],product=products.find(p=>p.name===entry?.product&&p.variant===entry?.variant);if(serverToken&&entry&&(entry.type==='in'||entry.type==='out')&&product)fetch(`${apiBase}/api/movements`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${serverToken}`},body:JSON.stringify({productId:product.id,type:entry.type,quantity:entry.qty,reference:entry.ref})}).catch(error=>console.warn('Server movement save unavailable.',error))},25));
document.querySelector('#movement-form').addEventListener('submit',()=>{skipNextStateSync=true;const product=products.find(p=>p.id===Number(document.querySelector('#product-select').value)),before=product?.stock,quantity=Number(document.querySelector('#quantity').value);setTimeout(()=>{if(activity[0]&&activity[0].type&&before!==undefined){activity[0].beforeStock=before;activity[0].afterStock=product.stock;activity[0].stockChange=quantity;save();render()}},0)},true);
let pendingDeleteId=null;
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-product]'),remove=e.target.closest('[data-delete-product]');if(edit&&currentRole==='admin'){const p=products.find(item=>item.id===Number(edit.dataset.editProduct));if(p)openProductModal(p)}if(remove&&currentRole==='admin'){const p=products.find(item=>item.id===Number(remove.dataset.deleteProduct));if(p){pendingDeleteId=p.id;$('#delete-product-description').textContent=`${p.name} · ${p.category||'Uncategorized'} · ${p.variant} currently has ${p.stock} pieces.`;$('#delete-modal').classList.remove('hidden')}}});
document.querySelector('#product-form').addEventListener('submit',e=>{if(!editingProductId)return;e.preventDefault();e.stopImmediatePropagation();const p=products.find(item=>item.id===editingProductId);if(p){const before=`${p.name} · ${p.category||'Uncategorized'} · ${p.code} · ${p.variant} · ${p.stock} pcs`;p.name=$('#new-name').value.trim();p.category=$('#new-category').value.trim();p.code=$('#new-code').value.trim()||p.code;p.variant=$('#new-variant').value.trim();p.stock=Math.max(0,Number($('#new-stock').value));p.price=Number($('#new-price').value) || 0;p.min=Math.max(0,Number($('#new-min').value));const after=`${p.name} · ${p.category} · ${p.code} · ${p.variant} · ${p.stock} pcs`;activity.unshift({type:'edit',product:p.name,variant:p.variant,before,after,time:'Just now'});save();editingProductId=null;$('#product-modal').classList.add('hidden');render()}},true);
$('#close-delete-modal').onclick=()=>$('#delete-modal').classList.add('hidden');$('#confirm-delete').onclick=()=>{if(pendingDeleteId!==null){const removed=products.find(item=>item.id===pendingDeleteId);products=products.filter(item=>item.id!==pendingDeleteId);activity.unshift({type:'delete',product:removed.name,variant:removed.variant,qty:removed.stock,ref:`Deleted by ${currentRole==='admin'?'Owner':'Entry Staff'}`,time:'Just now'});pendingDeleteId=null;save();$('#delete-modal').classList.add('hidden');render()}};
const totalStock = () => products.reduce((sum,p)=>sum+p.stock,0);
const lowStock = () => products.filter(p=>p.stock<=p.min);
const formatTime = value => value === 'Just now' ? 'Just now' : new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
function save(){activity.forEach(item=>{if(!item.createdAt)item.createdAt=new Date().toISOString()});localStorage.setItem('godown-products',JSON.stringify(products));if(serverToken&&!skipNextStateSync)fetch(`${apiBase}/api/state`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${serverToken}`},body:JSON.stringify({products,movements:activity})}).catch(error=>console.warn('Server save unavailable; local copy retained.',error));skipNextStateSync=false;}
function productRows(list=products){return list.map(p=>{const priceText = Number(p.price) ? ` · ₹${Number(p.price).toLocaleString('en-IN')}/pc` : ''; return `<tr><td class="product-cell">${p.name}<small>${p.category||'Uncategorized'} · ${p.code} · ${p.variant}${priceText}</small></td><td class="stock-number ${p.stock<=p.min?'stock-low':'stock-ok'}">${p.stock.toLocaleString()} pcs</td><td>${p.min} pcs</td><td><span class="pill ${p.stock<=p.min?'out':'in'}">${p.stock<=p.min?'Low stock':'In stock'}</span>${currentRole==='admin'?` <span class="row-actions"><button class="row-action" data-edit-product="${p.id}">Edit</button><button class="row-action delete" data-delete-product="${p.id}">Delete</button></span>`:''}</td></tr>`;}).join('') || '<tr><td colspan="4" class="empty">No matching products found</td></tr>';
}
function activityRows(list=activity.slice(0,5)){return list.map(a=>{const labels={in:['Stock received','↓',''],out:['Stock dispatched','↑','out'],edit:['Product edited','✎',''],delete:['Product deleted','×','out']},label=labels[a.type]||labels.edit;const movementDetail=(a.type==='in'||a.type==='out')&&a.beforeStock!==undefined?`<br><span class="audit-change"><b>Before:</b> ${a.beforeStock} pcs<br><b>${a.type==='in'?'Added':'Dispatched'}:</b> ${a.stockChange||a.qty} pcs<br><b>After:</b> ${a.afterStock} pcs</span>`:'';const editDetail=a.type==='edit'?`<br><span class="audit-change"><b>Before:</b> ${a.before}<br><b>After:</b> ${a.after}</span>`:'';return `<div class="activity-item"><div class="activity-icon ${label[2]}">${label[1]}</div><div><b>${label[0]}${a.qty?` · ${a.qty} pcs`:''}</b><p>${a.product} · ${a.variant}${movementDetail||editDetail||(!movementDetail&&!editDetail&&a.ref?`<br>${a.ref}`:'')}</p></div><time>${formatTime(a.createdAt||a.time)}</time></div>`}).join('') || '<div class="empty">No activity yet</div>';}
function emptyInventory(){return `<div class="empty">No products added yet. Start by entering your actual catalogue items and opening piece count.</div>`}
function movementActions(){return `<div><button class="primary-button" id="add-product">+ Add product</button> <button class="primary-button" id="import-excel" style="background:#d7a84f;color:#173d34">Import Excel ↥</button> <button class="primary-button" id="add-purchase">Purchase ↓</button> <button class="primary-button" id="add-sale" style="background:var(--orange)">Sale ↑</button></div>`}
function overview(){const today=new Date().toDateString();return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">LIVE SNAPSHOT · SINGLE GODOWN</div><h2>Stock at a glance</h2></div>${movementActions()}</div><div class="metric-grid"><div class="metric-card"><p>TOTAL PIECES</p><strong>${totalStock().toLocaleString()}</strong><small>↑ Live count</small></div><div class="metric-card"><p>PRODUCT VARIANTS</p><strong>${products.length}</strong><small>Added by you</small></div><div class="metric-card"><p>STOCK IN · TODAY</p><strong>${activity.filter(a=>a.type==='in'&&new Date(a.createdAt||a.time).toDateString()===today).reduce((s,a)=>s+a.qty,0).toLocaleString()}</strong><small>↑ Received</small></div><div class="metric-card"><p>LOW STOCK ITEMS</p><strong>${lowStock().length}</strong><small class="trend-down">Needs attention</small></div></div><div class="content-grid"><div class="panel"><div class="panel-head"><h3>Current inventory</h3><a data-go="inventory">View all →</a></div><div class="table-wrap">${products.length?`<table class="data-table"><thead><tr><th>Product / variant</th><th>Available</th><th>Alert at</th><th>Status</th></tr></thead><tbody>${productRows(products.slice(0,5))}</tbody></table>`:emptyInventory()}</div></div><div class="panel"><div class="panel-head"><h3>Recent activity</h3><a data-go="activity">View log →</a></div><div class="activity-list">${activityRows()}</div></div></div></section>`}
function inventory(){return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">PRODUCT MASTER · PIECES ONLY</div><h2>Inventory</h2></div>${movementActions()}</div><div class="search-bar"><span>⌕</span><input id="inventory-search" placeholder="Search product, category, code or finish..."/><select class="filter-select" id="stock-filter"><option value="all">All stock</option><option value="low">Low stock</option><option value="ok">In stock</option></select></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Product / category / variant</th><th>Available pieces</th><th>Alert threshold</th><th>Status</th></tr></thead><tbody id="inventory-body">${products.length?productRows():`<tr><td colspan="4">${emptyInventory()}</td></tr>`}</tbody></table></div></div></section>`}
function activityView(){return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">AUDIT TRAIL · EVERY MOVEMENT</div><h2>Activity log</h2></div><button class="primary-button" id="add-movement">+ Add movement</button></div><div class="panel"><div class="panel-head"><h3>All stock movements</h3><span class="eyebrow" style="margin:0">${activity.length} entries</span></div><div class="activity-list">${activityRows(activity)}</div></div></section>`}
function reports(){const ins=activity.filter(a=>a.type==='in').reduce((s,a)=>s+a.qty,0), outs=activity.filter(a=>a.type==='out').reduce((s,a)=>s+a.qty,0);return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">INSIGHTS · MOVEMENT SUMMARY</div><h2>Reports</h2></div><button class="primary-button" id="export-report">Export report <span>↓</span></button></div><div class="report-grid"><div class="report-card"><h3>Movement summary</h3><div class="bar-row"><div class="bar-label"><span>Stock received</span><b>${ins.toLocaleString()} pcs</b></div><div class="bar"><i style="width:${Math.min(100,ins/(ins+outs||1)*100)}%"></i></div></div><div class="bar-row"><div class="bar-label"><span>Stock dispatched</span><b>${outs.toLocaleString()} pcs</b></div><div class="bar"><i class="orange" style="width:${Math.min(100,outs/(ins+outs||1)*100)}%"></i></div></div></div><div class="report-card"><h3>Stock health</h3><div class="bar-row"><div class="bar-label"><span>Healthy variants</span><b>${products.length-lowStock().length} / ${products.length}</b></div><div class="bar"><i style="width:${(products.length-lowStock().length)/(products.length||1)*100}%"></i></div></div><div class="bar-row"><div class="bar-label"><span>Needs attention</span><b>${lowStock().length} variants</b></div><div class="bar"><i class="orange" style="width:${lowStock().length/(products.length||1)*100}%"></i></div></div></div><div class="report-card"><h3>Quick actions</h3><button class="primary-button" style="width:100%;margin-bottom:10px" id="report-movement">Record movement →</button><button class="filter-select" style="width:100%;cursor:pointer" id="whatsapp-report">Share summary on WhatsApp ↗</button></div></div></section>`}
function render(){const views={overview,inventory,activity:activityView,reports};$('#view-container').innerHTML=views[currentView]();$('#crumb-view').textContent=currentView.toUpperCase();$('#page-title').innerHTML=currentView==='overview'?'Good morning <span>✦</span>':currentView[0].toUpperCase()+currentView.slice(1);const roleName=currentRole==='admin'?'Owner':'Entry Staff',avatar=currentRole==='admin'?'OW':'ES';$('#user-name').textContent=roleName;$('#user-avatar').textContent=avatar;$('#sidebar-role').textContent=roleName;$('#sidebar-avatar').textContent=avatar;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));document.querySelectorAll('[data-admin-only]').forEach(x=>x.classList.toggle('hidden',currentRole!=='admin'));bindView();}
function openModal(type='in'){const sel=$('#product-select');sel.innerHTML=products.map(p=>`<option value="${p.id}">${p.name} · ${p.variant} (${p.stock} pcs)</option>`).join('');$('#movement-type').value=type;$('#modal-title').textContent=type==='out'?'Record sale / dispatch':'Add stock movement';$('#modal').classList.remove('hidden');$('#quantity').focus();}
let editingProductId = null;
function openProductModal(product=null){editingProductId=product?.id||null;$('#product-modal-title').textContent=product?'Edit product':'Add your product';$('#product-submit').innerHTML=product?'Save changes <span>→</span>':'Add product <span>→</span>';$('#new-name').value=product?.name||'';$('#new-category').value=product?.category||'';$('#new-code').value=product?.code||'';$('#new-variant').value=product?.variant||'';$('#new-stock').value=product?.stock??'';$('#new-price').value=product?.price ?? '';$('#new-min').value=product?.min??20;$('#product-modal').classList.remove('hidden');$('#new-name').focus()}
function bindView(){const add=$('#add-movement');if(add)add.onclick=openModal;const addPurchase=$('#add-purchase');if(addPurchase)addPurchase.onclick=()=>openModal('in');const addSale=$('#add-sale');if(addSale)addSale.onclick=()=>openModal('out');const addProduct=$('#add-product');if(addProduct){addProduct.onclick=openProductModal;if(currentRole!=='admin')addProduct.classList.add('hidden')}const importButton=$('#import-excel');if(importButton){importButton.onclick=()=>$('#excel-import').click();if(currentRole!=='admin')importButton.classList.add('hidden')}document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{currentView=x.dataset.go;render()});if(currentView==='inventory'){const update=()=>{const term=$('#inventory-search').value.toLowerCase(),filter=$('#stock-filter').value;let list=products.filter(p=>(p.name+p.category+p.code+p.variant).toLowerCase().includes(term)).filter(p=>filter==='all'||(filter==='low'?p.stock<=p.min:p.stock>p.min));$('#inventory-body').innerHTML=productRows(list)};$('#inventory-search').oninput=update;$('#stock-filter').onchange=update}if($('#export-report'))$('#export-report').onclick=()=>alert('Report export ready. Connect cloud storage to download PDF/Excel.');if($('#whatsapp-report'))$('#whatsapp-report').onclick=shareWhatsApp;if($('#report-movement'))$('#report-movement').onclick=openModal;}
function shareWhatsApp(){const text=`Godown stock summary\nTotal pieces: ${totalStock()}\nVariants: ${products.length}\nLow stock: ${lowStock().length}\nGenerated: ${new Date().toLocaleDateString('en-IN')}`;window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank')}
const normalizeHeader=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const findColumn=(row,names)=>{const key=Object.keys(row).find(item=>names.includes(normalizeHeader(item)));return key?row[key]:''};
document.querySelector('#excel-import').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(!window.XLSX){alert('Excel reader load nahi hua. Internet connection check karke page refresh karo.');return}try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''});let imported=0,skipped=0;rows.forEach(row=>{const name=String(findColumn(row,['product','item','productname','itemname','description'])).trim(),category=String(findColumn(row,['category','group','productcategory'])).trim()||'Uncategorized',code=String(findColumn(row,['code','sku','itemcode','productcode'])).trim()||`IMPORT-${Date.now()}-${imported}`,variant=String(findColumn(row,['variant','size','finish','sizefinish','model'])).trim()||'Standard',stock=Math.max(0,Number(findColumn(row,['stock','qty','quantity','pieces','closingstock','openingstock']))||0),min=Math.max(0,Number(findColumn(row,['minimum','minstock','alert','alertat']))||0);if(!name){skipped++;return}let product=products.find(p=>p.name.toLowerCase()===name.toLowerCase()&&p.category.toLowerCase()===category.toLowerCase()&&p.code.toLowerCase()===code.toLowerCase()&&p.variant.toLowerCase()===variant.toLowerCase());if(product){const before=product.stock;product.stock+=stock;activity.unshift({type:'in',product:product.name,category:product.category,variant:product.variant,qty:stock,beforeStock:before,afterStock:product.stock,stockChange:stock,ref:'Excel import - stock added',time:'Just now'})}else{product={id:Date.now()+imported,name,category,code,variant,stock,min};products.push(product);activity.unshift({type:'in',product:product.name,category:product.category,variant:product.variant,qty:stock,beforeStock:0,afterStock:stock,stockChange:stock,ref:'Excel import - opening stock',time:'Just now'})}imported++});save();render();alert(`${imported} products imported${skipped?`, ${skipped} rows skipped`:''}.`)}catch(error){alert('Excel file read nahi ho saki. Tally export ko .xlsx ya .csv format mein try karo.')}});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()});$('#logout-button').onclick=()=>{sessionStorage.removeItem('godown-role');currentRole=null;$('#login-screen').classList.remove('hidden');};$('#close-modal').onclick=()=>$('#modal').classList.add('hidden');$('#close-product-modal').onclick=()=>$('#product-modal').classList.add('hidden');document.querySelectorAll('.modal').forEach(modal=>modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')});$('#movement-form').onsubmit=e=>{e.preventDefault();const product=products.find(p=>p.id===Number($('#product-select').value)),type=$('#movement-type').value,qty=Number($('#quantity').value);if(!product)return;if(type==='out'&&qty>product.stock){alert('Available stock se zyada quantity dispatch nahi kar sakte.');return}product.stock+=type==='in'?qty:-qty;activity.unshift({type,product:product.name,variant:product.variant,qty,ref:$('#reference').value||'Manual entry',time:'Just now'});save();$('#modal').classList.add('hidden');e.target.reset();render()};$('#product-form').onsubmit=e=>{e.preventDefault();const name=$('#new-name').value.trim(),category=$('#new-category').value.trim(),code=$('#new-code').value.trim()||`SKU-${Date.now()}`,variant=$('#new-variant').value.trim(),openingStock=Number($('#new-stock').value),min=Number($('#new-min').value),existing=products.find(p=>p.name.toLowerCase()===name.toLowerCase()&&p.category.toLowerCase()===category.toLowerCase()&&p.code.toLowerCase()===code.toLowerCase()&&p.variant.toLowerCase()===variant.toLowerCase());if(existing){existing.stock+=openingStock;existing.min=min;activity.unshift({type:'in',product:existing.name,category:existing.category,variant:existing.variant,qty:openingStock,ref:'Opening stock added to existing product',time:'Just now'})}else{const product={id:Date.now(),name,category,code,variant,stock:openingStock,min};products.push(product);activity.unshift({type:'in',product:product.name,category:product.category,variant:product.variant,qty:product.stock,ref:'Opening stock',time:'Just now'})}save();$('#product-modal').classList.add('hidden');e.target.reset();render()};$('#login-form').onsubmit=e=>{e.preventDefault();const role=$('#login-role').value,user=$('#login-username').value.trim(),password=$('#login-password').value;if((role==='admin'&&user==='admin'&&password==='admin123')||(role==='staff'&&user==='staff'&&password==='staff123')){currentRole=role;sessionStorage.setItem('godown-role',role);$('#login-screen').classList.add('hidden');render()}else $('#login-error').textContent='Username or password is incorrect.'};if(currentRole)$('#login-screen').classList.add('hidden');render();
