import { auth, authReady, db } from './src/lib/firebase.js';
import { onAuthStateChanged, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { doc, onSnapshot, setDoc } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const stockLog = (message, details) => console.info(`[stock] ${message}`, details || '');
window.addEventListener('error',event=>console.error('[stock] runtime error',event.error||event.message));
window.addEventListener('unhandledrejection',event=>console.error('[stock] unhandled promise rejection',event.reason));
document.querySelector('#excel-import').addEventListener('change',()=>{products=products.map(product=>({...product,name:String(product?.name||''),category:String(product?.category||'Uncategorized'),code:String(product?.code||''),variant:String(product?.variant||'Standard')}));stockLog('Normalized inventory before Excel import',{products:products.length})},true);
document.addEventListener('keydown',event=>{if(typeof event.key!=='string')Object.defineProperty(event,'key',{value:''})},true);

const categoryStockSummary = (list=products) => {const totals={};list.forEach(product=>{const category=product.category||'Uncategorized';totals[category]=(totals[category]||0)+(Number(product.stock)||0)});return `<div class="category-stock-summary"><div class="category-summary-title">Category-wise stock</div><div class="category-summary-grid">${Object.entries(totals).sort((a,b)=>a[0].localeCompare(b[0])).map(([category,total])=>`<div class="category-summary-item"><span>${category}</span><strong>${total.toLocaleString()} pcs</strong></div>`).join('')||'<div class="empty">No category stock available</div>'}</div></div>`;};
const originalInventoryForCategorySummary=inventory;
inventory=function(){const markup=originalInventoryForCategorySummary();return markup.replace('<div class="panel"><div class="table-wrap">',`${categoryStockSummary()}<div class="panel"><div class="table-wrap">`)};
document.querySelector('#excel-import').addEventListener('change',async event=>{event.preventDefault();event.stopImmediatePropagation();const file=event.target.files[0];event.target.value='';if(!file||!window.XLSX)return;try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''});let imported=0,skipped=0;rows.forEach(row=>{const name=String(findColumn(row,['product','item','productname','itemname','description'])).trim(),category=String(findColumn(row,['category','group','productcategory'])).trim()||'Uncategorized',code=String(findColumn(row,['code','sku','itemcode','productcode'])).trim(),variant=String(findColumn(row,['variant','size','finish','sizefinish','sizevariant','model'])).trim()||'Standard',stock=Math.max(0,Number(findColumn(row,['stock','qty','quantity','pieces','closingstock','openingstock']))||0),price=Math.max(0,Number(findColumn(row,['price','rate','unitprice','priceperpiece','mrp','cost']))||0),min=Math.max(0,Number(findColumn(row,['minimum','minstock','minimumstock','alert','alertat']))||0);if(!name){skipped++;return}let product=code&&products.find(item=>String(item.code||'').toLowerCase()===code.toLowerCase());if(!product)product=products.find(item=>item.name.toLowerCase()===name.toLowerCase()&&String(item.variant||'').toLowerCase()===variant.toLowerCase());if(product){const before=product.stock,oldPrice=product.price||0;product.name=name;product.category=category;product.code=code||product.code||`SKU-${Date.now()}-${imported}`;product.variant=variant;product.price=price||oldPrice;product.min=min;product.stock+=stock;if(price&&price!==oldPrice)recordPriceChange(product,oldPrice,price,'Excel import');activity.unshift({type:'in',product:product.name,category,code:product.code,variant,price:price||oldPrice,transactionPrice:price||oldPrice,qty:stock,beforeStock:before,afterStock:product.stock,stockChange:stock,ref:'Excel import - updated by SKU',time:'Just now'})}else{product={id:Date.now()+imported,name,category,code:code||`SKU-${Date.now()}-${imported}`,variant,stock,price,min};products.push(product);activity.unshift({type:'in',product:name,category,code:product.code,variant,price,transactionPrice:price,qty:stock,beforeStock:0,afterStock:stock,stockChange:stock,ref:'Excel import - new product',time:'Just now'})}imported++});save();render();showToast(`${imported} products imported${skipped?`, ${skipped} rows skipped`:''}`,'success')}catch(error){showToast('Excel import failed. Check the template columns.','error')}},true);
function downloadImportTemplate(){const headers=['Product','Category','SKU','Size / Variant','Opening Stock','Price','Minimum Stock'];const sample=['Tower Bolt','Tower Bolt','142A','9mm Stainless Steel',100,245,20];if(window.XLSX){const workbook=XLSX.utils.book_new(),template=XLSX.utils.aoa_to_sheet([headers,sample]),instructions=XLSX.utils.aoa_to_sheet([['Column','What to enter'],['Product','Product name, required'],['Category','Category or product group'],['SKU','Unique product code'],['Size / Variant','Size, finish, model or variant'],['Opening Stock','Whole number of starting pieces'],['Price','Current price per piece'],['Minimum Stock','Alert threshold in pieces']]);XLSX.utils.book_append_sheet(workbook,template,'Import Template');XLSX.utils.book_append_sheet(workbook,instructions,'Instructions');XLSX.writeFile(workbook,'godown-stock-import-template.xlsx');return}const csv=[headers,sample].map(row=>row.join(',')).join('\r\n'),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='godown-stock-import-template.csv';link.click();}
document.addEventListener('click',e=>{if(e.target.closest('#download-template'))downloadImportTemplate()},true);
function enhanceOverviewSearch(){if(currentView!=='overview')return;const panel=document.querySelector('.content-grid .panel:first-child'),head=panel?.querySelector('.panel-head'),wrap=panel?.querySelector('.table-wrap');if(!head||!wrap)return;if(!panel.querySelector('.overview-category-summary')){const summary=document.createElement('div');summary.className='overview-category-summary';summary.innerHTML=categoryStockSummary(products).replace('category-stock-summary','overview-category-summary-inner');panel.insertBefore(summary,wrap)}if(head.querySelector('#overview-quick-search'))return;const search=document.createElement('input');search.id='overview-quick-search';search.className='quick-search';search.type='search';search.placeholder='Search SKU or size...';search.setAttribute('aria-label','Quick search inventory');head.insertBefore(search,head.querySelector('[data-go]'));const update=()=>{const term=search.value.trim().toLowerCase();const matches=products.filter(p=>`${p.name} ${p.category||''} ${p.code||''} ${p.variant||''}`.toLowerCase().includes(term));wrap.innerHTML=matches.length?`<table class="data-table"><thead><tr><th>Product / variant</th><th>Available</th><th>Alert at</th><th>Status</th></tr></thead><tbody>${productRows(matches.slice(0,5))}</tbody></table>`:`<div class="empty">No matching products found</div>`;};search.addEventListener('input',update);}
const saveBeforeOfflineQueue = save;
save = function(){saveBeforeOfflineQueue();if(navigator.onLine)saveFirebaseState().catch(error=>console.warn('Firestore save unavailable; local copy retained.',error));};
document.querySelector('#movement-form').addEventListener('submit',e=>{const type=document.querySelector('#movement-type')?.value;if(type&&!window.confirm(`Confirm ${type==='out'?'sale / dispatch':'purchase / stock receipt'}?`)){e.preventDefault();e.stopImmediatePropagation()}},true);
let undoDelete=null;
document.addEventListener('click',e=>{if(!e.target.closest('#confirm-delete'))return;e.preventDefault();e.stopImmediatePropagation();const removed=products.find(item=>item.id===pendingDeleteId);if(!removed)return;products=products.filter(item=>item.id!==pendingDeleteId);const deleteLog={type:'delete',product:removed.name,variant:removed.variant,qty:removed.stock,ref:`Deleted by ${currentRole==='admin'?'Owner':'Entry Staff'}`,time:'Just now'};activity.unshift(deleteLog);undoDelete={product:removed,activity:deleteLog};save();$('#delete-modal').classList.add('hidden');render();showToast('Product deleted. Press Ctrl+Z to undo.','info')},true);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&undoDelete){e.preventDefault();products.push(undoDelete.product);activity=activity.filter(item=>item!==undoDelete.activity);save();render();undoDelete=null;showToast('Product restored.','success')}});
document.querySelector('#excel-import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file||!window.XLSX)return;try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''}),seen=new Set(),duplicates=[];rows.forEach(row=>{const sku=String(findColumn(row,['code','sku','itemcode','productcode'])).trim().toLowerCase();if(sku&&(seen.has(sku)||products.some(p=>String(p.code||'').toLowerCase()===sku)))duplicates.push(sku);seen.add(sku)});if(duplicates.length)showToast(`${duplicates.length} duplicate SKU row(s) detected. Existing items will be matched, not duplicated.`,'info')}catch(error){showToast('Import preview could not be read.','error')}},true);
let deferredInstallPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});
if('serviceWorker' in navigator)navigator.serviceWorker.getRegistrations().then(registrations=>registrations.forEach(registration=>registration.unregister()));
const nativeAlert = window.alert.bind(window);
window.alert = message => { if(typeof showToast === 'function') showToast(String(message), 'info'); else nativeAlert(message); };
function showToast(message,type='info'){const region=document.querySelector('#toast-region');if(!region)return nativeAlert(message);const toast=document.createElement('div');toast.className=`toast ${type}`;toast.textContent=message;region.appendChild(toast);setTimeout(()=>toast.remove(),4200);}
function enhanceInventory(){const search=document.querySelector('#inventory-search'),body=document.querySelector('#inventory-body'),sort=document.querySelector('#inventory-sort'),pageSize=document.querySelector('#inventory-page-size'),pageLabel=document.querySelector('#inventory-page-label'),previous=document.querySelector('#inventory-prev'),next=document.querySelector('#inventory-next'),bulkMin=document.querySelector('#bulk-min'),bulkApply=document.querySelector('#bulk-apply');if(!search||!body)return;let page=1;const update=()=>{const term=search.value.toLowerCase(),filter=document.querySelector('#stock-filter')?.value||'all',size=Number(pageSize?.value||10);let list=products.filter(p=>(`${p.name} ${p.category||''} ${p.code||''} ${p.variant||''}`).toLowerCase().includes(term)).filter(p=>filter==='all'||(filter==='low'?p.stock<=p.min:p.stock>p.min));const mode=sort?.value||'name';list.sort((a,b)=>mode==='stock'?b.stock-a.stock:mode==='price'?(b.price||0)-(a.price||0):mode==='category'?(a.category||'').localeCompare(b.category||''):a.name.localeCompare(b.name));const pages=Math.max(1,Math.ceil(list.length/size));page=Math.min(page,pages);const visible=list.slice((page-1)*size,page*size);body.innerHTML=productRows(visible);if(pageLabel)pageLabel.textContent=`Page ${page} of ${pages} · ${list.length} products`;if(previous)previous.disabled=page===1;if(next)next.disabled=page===pages;};search.oninput=()=>{page=1;update()};document.querySelector('#stock-filter')?.addEventListener('change',()=>{page=1;update()});sort?.addEventListener('change',()=>{page=1;update()});pageSize?.addEventListener('change',()=>{page=1;update()});previous?.addEventListener('click',()=>{page--;update()});next?.addEventListener('click',()=>{page++;update()});bulkApply?.addEventListener('click',()=>{const value=Number(bulkMin?.value);if(!Number.isInteger(value)||value<0)return showToast('Enter a valid alert threshold.','error');const term=search.value.toLowerCase();products.filter(p=>(`${p.name} ${p.category||''} ${p.code||''} ${p.variant||''}`).toLowerCase().includes(term)).forEach(p=>p.min=value);save();render();showToast('Alert threshold updated for matching products.','success')});update();}
inventory=function(){return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">PRODUCT MASTER · PIECES ONLY</div><h2>Inventory</h2></div>${movementActions()}</div><div class="inventory-tools"><input id="inventory-search" placeholder="Search product, category, SKU or finish..." aria-label="Search inventory"/><select class="filter-select" id="stock-filter"><option value="all">All stock</option><option value="low">Low stock</option><option value="ok">In stock</option></select><select class="filter-select" id="inventory-sort" aria-label="Sort inventory"><option value="name">Sort: Product</option><option value="stock">Sort: Stock</option><option value="price">Sort: Price</option><option value="category">Sort: Category</option></select><select class="filter-select" id="inventory-page-size" aria-label="Products per page"><option value="10">10 / page</option><option value="25">25 / page</option><option value="50">50 / page</option></select></div><div class="bulk-bar"><span>Bulk alert threshold</span><input id="bulk-min" type="number" min="0" placeholder="pieces"/><button id="bulk-apply" type="button">Apply to search results</button></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Product / category / variant</th><th>Available pieces</th><th>Alert threshold</th><th>Status</th></tr></thead><tbody id="inventory-body">${products.length?productRows(products.slice(0,10)):`<tr><td colspan="4">${emptyInventory()}</td></tr>`}</tbody></table></div><div class="pagination"><span id="inventory-page-label">Page 1</span><div><button id="inventory-prev" type="button">← Previous</button> <button id="inventory-next" type="button">Next →</button></div></div></div></section>`};
const inventoryRendererWithTools=inventory;
inventory=function(){const markup=inventoryRendererWithTools();return markup.replace('</div><div class="inventory-tools">',`</div>${categoryStockSummary()}<div class="inventory-tools">`)};
const originalRenderForUx = render;
render = function(){originalRenderForUx();enhanceInventory();enhanceOverviewSearch();};
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal:not(.hidden)').forEach(modal=>modal.classList.add('hidden'));if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();currentView='inventory';render();document.querySelector('#inventory-search')?.focus()}if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))openModal('in');if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&e.key==='/'){if(!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();currentView='inventory';render();document.querySelector('#inventory-search')?.focus()}}});
document.querySelector('#theme-toggle')?.addEventListener('click',()=>{document.body.classList.toggle('dark-mode');localStorage.setItem('godown-dark-mode',document.body.classList.contains('dark-mode')?'1':'0');showToast(document.body.classList.contains('dark-mode')?'Dark mode enabled':'Light mode enabled','success')});
if(localStorage.getItem('godown-dark-mode')==='1')document.body.classList.add('dark-mode');
window.addEventListener('offline',()=>document.querySelector('#offline-indicator')?.classList.remove('hidden'));window.addEventListener('online',()=>{document.querySelector('#offline-indicator')?.classList.add('hidden');showToast('Connection restored. Local data is ready to sync.','success')});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>showToast('Offline mode could not be enabled.','error')));
queueMicrotask(()=>{authReady.then(()=>signInAnonymously(auth)).catch(error=>console.warn('Background Firebase sync unavailable.',error));if(currentRole==='admin'){document.querySelector('#login-screen').classList.add('hidden');document.querySelector('.app-shell').classList.add('ready');render();}});
document.addEventListener('click',event=>{if(event.target.closest('#add-product')){event.preventDefault();event.stopImmediatePropagation();openProductModal();}},true);
document.addEventListener('click',event=>{const sidebar=document.querySelector('.sidebar');if(!sidebar)return;if(event.target.closest('#mobile-menu')){sidebar.classList.toggle('open');document.body.classList.toggle('mobile-nav-open',sidebar.classList.contains('open'));return}if(sidebar.classList.contains('open')&&(!event.target.closest('.sidebar')||event.target.closest('.nav-item'))){sidebar.classList.remove('open');document.body.classList.remove('mobile-nav-open')}},true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'){document.querySelector('.sidebar')?.classList.remove('open');document.body.classList.remove('mobile-nav-open')}},true);
exportReport=function(){const r=reportRows(),rows=[['SECTION','PRODUCTS'],['Product','Category','SKU','Size / Variant','Current Price','Stock','Minimum'],...products.map(p=>[p.name,p.category||'Uncategorized',p.code||'',p.variant||'',p.price||0,p.stock,p.min]),[],['SECTION','PRICE HISTORY'],['Product','Old Price','New Price','Changed By','Changed Date','Reason'],...priceHistory.map(h=>[h.product,h.oldPrice,h.newPrice,h.changedBy,h.changedAt,h.reason]),[],['SECTION','PURCHASES'],['Product','Supplier / Reference','Transaction Price','Quantity','Date'],...r.purchases.map(a=>[a.product,a.ref||'',a.transactionPrice??a.price??0,a.qty||0,a.createdAt||a.time||'']),[],['SECTION','SALES'],['Product','Customer / Reference','Transaction Price','Quantity','Date'],...r.sales.map(a=>[a.product,a.ref||'',a.transactionPrice??a.price??0,a.qty||0,a.createdAt||a.time||'']),[],['SECTION','CATEGORY STOCK'],['Category','Pieces'],...Object.entries(r.byCategory),[],['SECTION','SUPPLIER PURCHASES'],['Supplier','Pieces'],...Object.entries(r.bySupplier),[],['SECTION','LOW STOCK'],['Product','Stock','Minimum'],...r.low.map(p=>[p.name,p.stock,p.min]),[],['SECTION','OUT OF STOCK'],['Product','Stock','Minimum'],...r.out.map(p=>[p.name,p.stock,p.min]),[],['SECTION','FAST MOVING'],['Product','Sold Pieces'],...r.fast.map(p=>[p.name,activity.filter(a=>a.product===p.name&&a.type==='out').reduce((s,a)=>s+(a.qty||0),0)]),[],['SECTION','SLOW MOVING'],['Product','Sales Count'],...r.slow.map(p=>[p.name,activity.filter(a=>a.product===p.name&&a.type==='out').length]),[],['SECTION','DEAD STOCK'],['Product','Stock'],...r.dead.map(p=>[p.name,p.stock])];const csv=rows.map(row=>row.map(value=>`"${String(value??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`godown-complete-report-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);};
document.querySelector('#excel-import').addEventListener('change',async e=>{e.preventDefault();e.stopImmediatePropagation();const file=e.target.files[0];e.target.value='';if(!file||!window.XLSX)return;const rows=XLSX.utils.sheet_to_json(XLSX.read(await file.arrayBuffer(),{type:'array'}).Sheets[XLSX.read(await file.arrayBuffer(),{type:'array'}).SheetNames[0]],{defval:''});let imported=0;rows.forEach(row=>{const name=String(findColumn(row,['product','item','productname','itemname','description'])).trim();if(!name)return;const category=String(findColumn(row,['category','group','productcategory'])).trim()||'Uncategorized',code=String(findColumn(row,['code','sku','itemcode','productcode'])).trim()||`IMPORT-${Date.now()}-${imported}`,variant=String(findColumn(row,['variant','size','finish','sizefinish','model'])).trim()||'Standard',price=Math.max(0,Number(findColumn(row,['price','rate','unitprice','priceperpiece','mrp','cost']))||0),stock=Math.max(0,Number(findColumn(row,['stock','qty','quantity','pieces','closingstock','openingstock']))||0),min=Math.max(0,Number(findColumn(row,['minimum','minstock','alert','alertat']))||0);let product=products.find(p=>p.name.toLowerCase()===name.toLowerCase()&&p.category.toLowerCase()===category.toLowerCase()&&p.code.toLowerCase()===code.toLowerCase()&&p.variant.toLowerCase()===variant.toLowerCase());if(product){const oldPrice=product.price||0;if(price&&price!==oldPrice){recordPriceChange(product,oldPrice,price,'Excel import');product.price=price}const before=product.stock;product.stock+=stock;activity.unshift({type:'in',product:product.name,category,code,variant,price,transactionPrice:price,qty:stock,beforeStock:before,afterStock:product.stock,stockChange:stock,ref:'Excel import',time:'Just now'})}else{product={id:Date.now()+imported,name,category,code,variant,stock,price,min};products.push(product);activity.unshift({type:'in',product:name,category,code,variant,price,transactionPrice:price,qty:stock,beforeStock:0,afterStock:stock,stockChange:stock,ref:'Excel import',time:'Just now'})}imported++});save();render();alert(`${imported} products imported.`)},true);
const persistPriceHistory = () => { localStorage.setItem('godown-price-history',JSON.stringify(priceHistory)); if(firebaseUser&&!skipNextStateSync)saveFirebaseState().catch(error=>console.warn('Price history save unavailable.',error)); };
const originalSave = save;
save = function(){ originalSave(); persistPriceHistory(); const critical=products.filter(p=>p.stock<=0||p.stock<=p.min); const key=critical.map(p=>`${p.id}:${p.stock}`).join('|'); if(key&&key!==lastAlertKey){lastAlertKey=key;notifyTelegram(`Godown Alert\n${critical.some(p=>p.stock<=0)?'Out of stock / ':''}Low stock items\n${critical.map(p=>`${p.name}: ${p.stock} pcs (alert ${p.min})`).join('\n')}`);} };
const originalLoadServerState = loadServerState;
loadServerState = async function(){await originalLoadServerState();notifyTelegram(`Godown Login Alert\nRole: ${currentRole==='admin'?'Owner':'Entry Staff'}\nTime: ${new Date().toLocaleString('en-IN')}`);};
reports=function(){const r=reportRows(),purchaseQty=r.purchases.reduce((s,a)=>s+(Number(a.qty)||0),0),salesQty=r.sales.reduce((s,a)=>s+(Number(a.qty)||0),0),purchaseValue=r.purchases.reduce((s,a)=>s+(Number(a.qty)||0)*(Number(a.transactionPrice??a.price)||0),0),salesValue=r.sales.reduce((s,a)=>s+(Number(a.qty)||0)*(Number(a.transactionPrice??a.price)||0),0);const list=(items,field)=>items.slice(0,5).map(p=>`<div class="bar-row"><div class="bar-label"><span>${p.name}</span><b>${field(p)}</b></div></div>`).join('')||'<div class="empty">No data</div>';return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">INSIGHTS · COMPLETE STOCK REPORT</div><h2>Reports</h2></div><div><button class="primary-button" id="export-report">Export CSV <span>↓</span></button> <button class="primary-button" id="export-pdf">Print / PDF</button> <button class="primary-button" id="telegram-summary">Telegram closing summary</button></div></div><div class="metric-grid"><div class="metric-card"><p>PURCHASES</p><strong>${purchaseQty.toLocaleString()}</strong><small>${money(purchaseValue)}</small></div><div class="metric-card"><p>SALES</p><strong>${salesQty.toLocaleString()}</strong><small>${money(salesValue)}</small></div><div class="metric-card"><p>GROSS VALUE</p><strong>${money(salesValue-purchaseValue)}</strong><small>Sales value minus purchase value</small></div><div class="metric-card"><p>LOW / OUT</p><strong>${r.low.length} / ${r.out.length}</strong><small>Needs attention</small></div></div><div class="report-grid"><div class="report-card"><h3>Category-wise stock</h3>${Object.entries(r.byCategory).map(([key,value])=>`<div class="bar-row"><div class="bar-label"><span>${key}</span><b>${value} pcs</b></div></div>`).join('')||'<div class="empty">No data</div>'}</div><div class="report-card"><h3>Supplier-wise purchases</h3>${Object.entries(r.bySupplier).map(([key,value])=>`<div class="bar-row"><div class="bar-label"><span>${key}</span><b>${value} pcs</b></div></div>`).join('')||'<div class="empty">No data</div>'}</div><div class="report-card"><h3>Fast-moving products</h3>${list(r.fast,p=>`${activity.filter(a=>a.product===p.name&&a.type==='out').reduce((s,a)=>s+(a.qty||0),0)} pcs sold`)}</div><div class="report-card"><h3>Slow-moving products</h3>${list(r.slow,p=>`${activity.filter(a=>a.product===p.name&&a.type==='out').length} sales`)}</div><div class="report-card"><h3>Dead stock</h3>${list(r.dead,p=>`${p.stock} pcs`)}</div><div class="report-card"><h3>Price change history</h3>${priceHistory.slice(0,8).map(h=>`<div class="bar-row"><div class="bar-label"><span>${h.product}</span><b>${money(h.oldPrice)} → ${money(h.newPrice)}</b></div></div>`).join('')||'<div class="empty">No price changes yet</div>'}</div></div></section>`};
let priceHistory = JSON.parse(localStorage.getItem('godown-price-history')) || [];
let lastAlertKey = '';
const recordPriceChange = (product, oldPrice, newPrice, reason='Product edit') => { if (Number(oldPrice) === Number(newPrice)) return; const entry = { id: Date.now() + Math.random(), productId: product.id, product: product.name, category: product.category, code: product.code, variant: product.variant, oldPrice: Number(oldPrice)||0, newPrice: Number(newPrice)||0, changedBy: currentRole === 'admin' ? 'Owner' : 'Entry Staff', changedAt: new Date().toISOString(), reason }; priceHistory.unshift(entry); return entry; };
const reportRows = () => { const purchases=activity.filter(a=>a.type==='in'), sales=activity.filter(a=>a.type==='out'), byCategory={}, bySupplier={}; products.forEach(p=>{const key=p.category||'Uncategorized';byCategory[key]=(byCategory[key]||0)+p.stock;}); purchases.forEach(a=>{const key=a.ref||'Unknown supplier';bySupplier[key]=(bySupplier[key]||0)+(Number(a.qty)||0);}); return { purchases, sales, byCategory, bySupplier, low:products.filter(p=>p.stock>0&&p.stock<=p.min), out:products.filter(p=>p.stock<=0), fast:[...products].sort((a,b)=>activity.filter(x=>x.product===b.name&&x.type==='out').reduce((s,x)=>s+x.qty,0)-activity.filter(x=>x.product===a.name&&x.type==='out').reduce((s,x)=>s+x.qty,0)).slice(0,10), slow:[...products].sort((a,b)=>activity.filter(x=>x.product===a.name&&x.type==='out').length-activity.filter(x=>x.product===b.name&&x.type==='out').length).slice(0,10), dead:products.filter(p=>!activity.some(a=>a.product===p.name&&a.type==='out'))}; };
document.querySelector('#movement-form').addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();const product=products.find(p=>p.id===Number($('#product-select').value)),type=$('#movement-type').value,qty=Number($('#quantity').value),transactionPrice=Number($('#movement-price').value)||Number(product?.price)||0;if(!product)return;if(!Number.isInteger(qty)||qty<1){alert('Quantity must be a positive whole number.');return}if(type==='out'&&qty>product.stock){notifyTelegram(`Godown Alert\nFailed movement: insufficient stock\nProduct: ${product.name}\nRequested: ${qty} pcs\nAvailable: ${product.stock} pcs`);alert('Available stock se zyada quantity dispatch nahi kar sakte.');return}const beforeStock=product.stock;product.stock+=type==='in'?qty:-qty;const reference=$('#reference').value||'Manual entry';activity.unshift({type,product:product.name,category:product.category,code:product.code,variant:product.variant,price:transactionPrice,transactionPrice,qty,beforeStock,afterStock:product.stock,stockChange:qty,ref:reference,time:'Just now'});save();$('#modal').classList.add('hidden');e.target.reset();render()},true);
document.querySelector('#product-form').addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();const name=$('#new-name').value.trim(),category=$('#new-category').value.trim(),code=$('#new-code').value.trim()||`SKU-${Date.now()}`,variant=$('#new-variant').value.trim(),stock=Math.max(0,Number($('#new-stock').value)||0),newPrice=Math.max(0,Number($('#new-price').value)||0),min=Math.max(0,Number($('#new-min').value)||0),product=editingProductId&&products.find(item=>item.id===editingProductId);if(product){const oldPrice=product.price||0;product.name=name;product.category=category;product.code=code;product.variant=variant;product.stock=stock;product.min=min;product.price=newPrice;recordPriceChange(product,oldPrice,newPrice,'Product edit');activity.unshift({type:'edit',product:product.name,category,code,variant,before:`Price ${money(oldPrice)}`,after:`Price ${money(newPrice)}`,price:newPrice,time:'Just now'});}else{const created={id:Date.now(),name,category,code,variant,stock,price:newPrice,min};products.push(created);activity.unshift({type:'in',product:name,category,code,variant,price:newPrice,transactionPrice:newPrice,qty:stock,beforeStock:0,afterStock:stock,stockChange:stock,ref:'Opening stock',time:'Just now'});}save();editingProductId=null;$('#product-modal').classList.add('hidden');e.target.reset();render()},true);
document.addEventListener('click',e=>{if(e.target.closest('#export-pdf')){window.print()}if(e.target.closest('#telegram-summary')){const r=reportRows();notifyTelegram(`Daily Closing Summary\nTotal pieces: ${totalStock()}\nProducts: ${products.length}\nPurchases: ${r.purchases.reduce((s,a)=>s+(a.qty||0),0)} pcs\nSales: ${r.sales.reduce((s,a)=>s+(a.qty||0),0)} pcs\nLow stock: ${r.low.length}\nOut of stock: ${r.out.length}\nDate: ${new Date().toLocaleString('en-IN')}`);alert('Daily summary Telegram par bhej diya gaya.') }},true);
document.querySelector('#excel-import').addEventListener('change',async e=>{e.preventDefault();e.stopImmediatePropagation();const file=e.target.files[0];e.target.value='';if(!file)return;if(!window.XLSX){alert('Excel reader load nahi hua.');return}const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''});let imported=0,skipped=0;rows.forEach(row=>{const name=String(findColumn(row,['product','item','productname','itemname','description'])).trim(),category=String(findColumn(row,['category','group','productcategory'])).trim()||'Uncategorized',code=String(findColumn(row,['code','sku','itemcode','productcode'])).trim()||`IMPORT-${Date.now()}-${imported}`,variant=String(findColumn(row,['variant','size','finish','sizefinish','model'])).trim()||'Standard',stock=Math.max(0,Number(findColumn(row,['stock','qty','quantity','pieces','closingstock','openingstock']))||0),price=Math.max(0,Number(findColumn(row,['price','rate','unitprice','priceperpiece','mrp','cost']))||0),min=Math.max(0,Number(findColumn(row,['minimum','minstock','alert','alertat']))||0);if(!name){skipped++;return}let product=products.find(p=>p.name.toLowerCase()===name.toLowerCase()&&p.category.toLowerCase()===category.toLowerCase()&&p.code.toLowerCase()===code.toLowerCase()&&p.variant.toLowerCase()===variant.toLowerCase());if(product){const before=product.stock;product.stock+=stock;product.price=price||product.price||0;activity.unshift({type:'in',product:product.name,category:product.category,code:product.code,variant:product.variant,price:product.price,qty:stock,beforeStock:before,afterStock:product.stock,stockChange:stock,ref:'Excel import - stock added',time:'Just now'})}else{product={id:Date.now()+imported,name,category,code,variant,stock,price,min};products.push(product);activity.unshift({type:'in',product:product.name,category,code,variant,price,qty:stock,beforeStock:0,afterStock:stock,stockChange:stock,ref:'Excel import - opening stock',time:'Just now'})}imported++});save();render();alert(`${imported} products imported${skipped?`, ${skipped} rows skipped`:''}`)},true);
document.querySelector('#movement-form').addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();const product=products.find(p=>p.id===Number($('#product-select').value)),type=$('#movement-type').value,qty=Number($('#quantity').value),price=Number($('#movement-price').value)||Number(product?.price)||0;if(!product)return;if(!Number.isInteger(qty)||qty<1){alert('Quantity must be a positive whole number.');return}if(type==='out'&&qty>product.stock){alert('Available stock se zyada quantity dispatch nahi kar sakte.');return}const beforeStock=product.stock;product.stock+=type==='in'?qty:-qty;product.price=price;const reference=$('#reference').value||'Manual entry';activity.unshift({type,product:product.name,category:product.category,code:product.code,variant:product.variant,price,qty,beforeStock,afterStock:product.stock,stockChange:qty,ref:reference,time:'Just now'});save();$('#modal').classList.add('hidden');e.target.reset();render()},true);
if(location.protocol==='file:')location.replace('http://localhost:3000');
let products = JSON.parse(localStorage.getItem('godown-products')) || [];
let activity = JSON.parse(localStorage.getItem('godown-activity')) || [];
let savedProductCount = products.length;
let pendingCategory = '';
let pendingPrice = 0;
document.querySelector('#product-form').addEventListener('submit',()=>{pendingCategory=document.querySelector('#new-category').value.trim();pendingPrice=Number(document.querySelector('#new-price').value)||0});
setInterval(()=>{if(products.length>savedProductCount){products[products.length-1].category=products[products.length-1].category||pendingCategory||'Uncategorized';products[products.length-1].price=products[products.length-1].price||pendingPrice;savedProductCount=products.length;save()}},100);
if (products.some(p => ['ALD-04-ANT', 'MH-06-SS', 'TB-08-BLK', 'DH-03-SS', 'ALD-06-GOL', 'CK-32-BRS'].includes(p.code))) {
	products = [];
	activity = [];
	localStorage.removeItem('godown-products');
	localStorage.removeItem('godown-activity');
}
let currentView = 'overview';
let currentRole = sessionStorage.getItem('godown-role');
let firebaseUser = auth.currentUser;
let sharedStateReady = false;
const sharedInventoryRef = doc(db,'inventory','shared');
let skipNextStateSync = false;
const userEmail = username => username.includes('@') ? username.toLowerCase() : `${username.toLowerCase()}@legal-stock-control.firebaseapp.com`;
document.querySelector('#login-form').addEventListener('submit',event=>{event.preventDefault();event.stopImmediatePropagation();const username=document.querySelector('#login-username').value.trim().toLowerCase(),password=document.querySelector('#login-password').value;if(username!=='admin'||password!=='admin123'){document.querySelector('#login-error').textContent='Use admin as username and admin123 as password.';return}currentRole='admin';sessionStorage.setItem('godown-role','admin');document.querySelector('#login-error').textContent='';document.querySelector('#login-screen').classList.add('hidden');document.querySelector('.app-shell').classList.add('ready');render()},true);
async function loadServerState(){if(!firebaseUser){stockLog('Firestore sync waiting for anonymous auth');return}try{stockLog('Starting realtime listener',sharedInventoryRef.path);onSnapshot(sharedInventoryRef,snapshot=>{const state=snapshot.exists()?snapshot.data():{};stockLog('Realtime snapshot received',{exists:snapshot.exists(),products:(state.products||[]).length});if(snapshot.exists()){products=state.products||[];activity=state.movements||[];priceHistory=state.priceHistory||priceHistory;localStorage.setItem('godown-products',JSON.stringify(products));localStorage.setItem('godown-activity',JSON.stringify(activity));localStorage.setItem('godown-price-history',JSON.stringify(priceHistory));}else if(products.length||activity.length||priceHistory.length){saveFirebaseState().catch(error=>console.error('[stock] initial Firestore upload failed',error))}sharedStateReady=true;if(currentRole==='admin'){document.querySelector('#login-screen').classList.add('hidden');document.querySelector('.app-shell').classList.add('ready');render()}} ,error=>console.error('[stock] realtime Firestore listener failed',error))}catch(error){console.error('[stock] Firestore listener setup failed',error)}}
async function saveFirebaseState(){if(!firebaseUser||!sharedStateReady||skipNextStateSync){stockLog('Firestore save skipped',{hasUser:Boolean(firebaseUser),ready:sharedStateReady,skipped:skipNextStateSync});return}stockLog('Saving shared inventory',{products:products.length,movements:activity.length});try{await setDoc(sharedInventoryRef,{products,movements:activity,priceHistory,updatedAt:new Date().toISOString()},{merge:true});stockLog('Shared inventory saved')}catch(error){console.error('[stock] Firestore save failed',error);throw error}}
document.querySelector('#login-form').addEventListener('submit',event=>{event.preventDefault();event.stopImmediatePropagation();const username=document.querySelector('#login-username').value.trim().toLowerCase(),password=document.querySelector('#login-password').value;if(username!=='admin'||password!=='admin123'){document.querySelector('#login-error').textContent='Use admin as username and admin123 as password.';return}currentRole='admin';sessionStorage.setItem('godown-role','admin');document.querySelector('#login-error').textContent='';document.querySelector('#login-screen').classList.add('hidden');document.querySelector('.app-shell').classList.add('ready');render()},true);
onAuthStateChanged(auth,user=>{firebaseUser=user;stockLog('Firebase auth state changed',{anonymousUser:Boolean(user),uid:user?.uid});if(user)loadServerState().catch(error=>console.error('[stock] realtime sync unavailable',error))});
document.querySelector('#logout-button').addEventListener('click',()=>document.querySelector('.app-shell').classList.remove('ready'));
const $ = (q) => document.querySelector(q);
document.querySelector('#movement-form').addEventListener('submit',()=>{skipNextStateSync=true;const product=products.find(p=>p.id===Number(document.querySelector('#product-select').value)),before=product?.stock,quantity=Number(document.querySelector('#quantity').value);setTimeout(()=>{if(activity[0]&&activity[0].type&&before!==undefined){activity[0].beforeStock=before;activity[0].afterStock=product.stock;activity[0].stockChange=quantity;save();render()}},0)},true);
let pendingDeleteId=null;
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-product]'),remove=e.target.closest('[data-delete-product]');if(edit&&currentRole==='admin'){const p=products.find(item=>item.id===Number(edit.dataset.editProduct));if(p)openProductModal(p)}if(remove&&currentRole==='admin'){const p=products.find(item=>item.id===Number(remove.dataset.deleteProduct));if(p){pendingDeleteId=p.id;$('#delete-product-description').textContent=`${p.name} · ${p.category||'Uncategorized'} · ${p.variant} currently has ${p.stock} pieces.`;$('#delete-modal').classList.remove('hidden')}}});
document.querySelector('#product-form').addEventListener('submit',e=>{if(!editingProductId)return;e.preventDefault();e.stopImmediatePropagation();const p=products.find(item=>item.id===editingProductId);if(p){const before=`${p.name} · ${p.category||'Uncategorized'} · ${p.code} · ${p.variant} · ${p.stock} pcs`;p.name=$('#new-name').value.trim();p.category=$('#new-category').value.trim();p.code=$('#new-code').value.trim()||p.code;p.variant=$('#new-variant').value.trim();p.stock=Math.max(0,Number($('#new-stock').value));p.price=Number($('#new-price').value) || 0;p.min=Math.max(0,Number($('#new-min').value));const after=`${p.name} · ${p.category} · ${p.code} · ${p.variant} · ${p.stock} pcs`;activity.unshift({type:'edit',product:p.name,variant:p.variant,before,after,time:'Just now'});save();editingProductId=null;$('#product-modal').classList.add('hidden');render()}},true);
$('#close-delete-modal').onclick=()=>$('#delete-modal').classList.add('hidden');$('#confirm-delete').onclick=()=>{if(pendingDeleteId!==null){const removed=products.find(item=>item.id===pendingDeleteId);products=products.filter(item=>item.id!==pendingDeleteId);activity.unshift({type:'delete',product:removed.name,variant:removed.variant,qty:removed.stock,ref:`Deleted by ${currentRole==='admin'?'Owner':'Entry Staff'}`,time:'Just now'});pendingDeleteId=null;save();$('#delete-modal').classList.add('hidden');render()}};
const totalStock = () => products.reduce((sum,p)=>sum+p.stock,0);
const lowStock = () => products.filter(p=>p.stock<=p.min);
const formatTime = value => value === 'Just now' ? 'Just now' : new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
const money = value => `₹${Number(value||0).toLocaleString('en-IN')}`;
function notifyTelegram(text){if(!firebaseUser)return;fetch('/.netlify/functions/telegram-notify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})}).then(response=>{if(!response.ok)throw new Error(`Telegram function returned ${response.status}`);stockLog('Telegram notification sent')}).catch(error=>console.warn('[stock] Telegram notification unavailable.',error));}
function productTelegramText(action,product,extra=''){return `Godown Stock Log\nAction: ${action}\nProduct: ${product.name}\nCategory: ${product.category||'Uncategorized'}\nSKU: ${product.code||'-'}\nSize / Variant: ${product.variant||'-'}\nPrice: ${money(product.price)}/pc\nStock: ${product.stock} pcs${extra?`\n${extra}`:''}\nDate: ${new Date().toLocaleString('en-IN')}\nBy: ${currentRole==='admin'?'Owner':'Entry Staff'}`;}
let lastTelegramActivityKey = '';
function notifyLatestActivity(){const item=activity[0];if(!item)return;const key=`${item.createdAt||item.time}|${item.type}|${item.product}|${item.variant}|${item.qty||''}`;if(key===lastTelegramActivityKey)return;lastTelegramActivityKey=key;const product=products.find(p=>p.name===item.product&&p.variant===item.variant)||{name:item.product,category:item.category,code:item.code,variant:item.variant,price:item.price,stock:item.afterStock??item.qty??0};notifyTelegram(productTelegramText(item.type==='in'?'Purchase / stock received':item.type==='out'?'Sale / stock dispatched':item.type==='edit'?'Product edited':'Product deleted',product,`Quantity: ${item.qty||'-'} pcs\nReference: ${item.ref||item.after||'-'}`));}
function exportReport(){const rows=[['Product','Category','SKU','Size / Variant','Price per piece','Stock','Low-stock alert'],...products.map(p=>[p.name,p.category||'Uncategorized',p.code||'',p.variant||'',p.price||0,p.stock,p.min])];activity.forEach(a=>rows.push(['LOG',a.type,a.product,a.variant,a.price||0,a.qty||'',a.ref||'']));const csv=rows.map(row=>row.map(value=>`"${String(value??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`godown-stock-report-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);}
function save(){activity.forEach(item=>{if(!item.createdAt)item.createdAt=new Date().toISOString()});localStorage.setItem('godown-products',JSON.stringify(products));notifyLatestActivity();if(firebaseUser&&!skipNextStateSync)saveFirebaseState().catch(error=>console.warn('Firestore save unavailable; local copy retained.',error));skipNextStateSync=false;}
function productRows(list=products){return list.map(p=>{const priceText = Number(p.price) ? ` · ₹${Number(p.price).toLocaleString('en-IN')}/pc` : ''; return `<tr><td class="product-cell">${p.name}<small>${p.category||'Uncategorized'} · ${p.code} · ${p.variant}${priceText}</small></td><td class="stock-number ${p.stock<=p.min?'stock-low':'stock-ok'}">${p.stock.toLocaleString()} pcs</td><td>${p.min} pcs</td><td><span class="pill ${p.stock<=p.min?'out':'in'}">${p.stock<=p.min?'Low stock':'In stock'}</span>${currentRole==='admin'?` <span class="row-actions"><button class="row-action" data-edit-product="${p.id}">Edit</button><button class="row-action delete" data-delete-product="${p.id}">Delete</button></span>`:''}</td></tr>`;}).join('') || '<tr><td colspan="4" class="empty">No matching products found</td></tr>';
}
function activityRows(list=activity.slice(0,5)){return list.map(a=>{const labels={in:['Stock received','↓',''],out:['Stock dispatched','↑','out'],edit:['Product edited','✎',''],delete:['Product deleted','×','out']},label=labels[a.type]||labels.edit;const movementDetail=(a.type==='in'||a.type==='out')&&a.beforeStock!==undefined?`<br><span class="audit-change"><b>Price:</b> ${money(a.price)}/pc<br><b>Before:</b> ${a.beforeStock} pcs<br><b>${a.type==='in'?'Added':'Dispatched'}:</b> ${a.stockChange||a.qty} pcs<br><b>After:</b> ${a.afterStock} pcs</span>`:'';const editDetail=a.type==='edit'?`<br><span class="audit-change"><b>Before:</b> ${a.before}<br><b>After:</b> ${a.after}</span>`:'';return `<div class="activity-item"><div class="activity-icon ${label[2]}">${label[1]}</div><div><b>${label[0]}${a.qty?` · ${a.qty} pcs`:''}</b><p>${a.product} · ${a.variant}${movementDetail||editDetail||(!movementDetail&&!editDetail&&a.ref?`<br>${a.ref}`:'')}</p></div><time>${formatTime(a.createdAt||a.time)}</time></div>`}).join('') || '<div class="empty">No activity yet</div>';}
function emptyInventory(){return `<div class="empty">No products added yet. Start by entering your actual catalogue items and opening piece count.</div>`}
function movementActions(){return `<div><button class="primary-button" id="add-product">+ Add product</button> <button class="primary-button" id="import-excel" style="background:#d7a84f;color:#173d34">Import Excel ↥</button> <button class="primary-button" id="download-template" style="background:#eef4f0;color:var(--green)">Download template ↓</button> <button class="primary-button" id="add-purchase">Purchase ↓</button> <button class="primary-button" id="add-sale" style="background:var(--orange)">Sale ↑</button></div>`}
function overview(){const today=new Date().toDateString();return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">LIVE SNAPSHOT · SINGLE GODOWN</div><h2>Stock at a glance</h2></div>${movementActions()}</div><div class="metric-grid"><div class="metric-card"><p>TOTAL PIECES</p><strong>${totalStock().toLocaleString()}</strong><small>↑ Live count</small></div><div class="metric-card"><p>PRODUCT VARIANTS</p><strong>${products.length}</strong><small>Added by you</small></div><div class="metric-card"><p>STOCK IN · TODAY</p><strong>${activity.filter(a=>a.type==='in'&&new Date(a.createdAt||a.time).toDateString()===today).reduce((s,a)=>s+a.qty,0).toLocaleString()}</strong><small>↑ Received</small></div><div class="metric-card"><p>LOW STOCK ITEMS</p><strong>${lowStock().length}</strong><small class="trend-down">Needs attention</small></div></div><div class="content-grid"><div class="panel"><div class="panel-head"><h3>Current inventory</h3><a data-go="inventory">View all →</a></div><div class="table-wrap">${products.length?`<table class="data-table"><thead><tr><th>Product / variant</th><th>Available</th><th>Alert at</th><th>Status</th></tr></thead><tbody>${productRows(products.slice(0,5))}</tbody></table>`:emptyInventory()}</div></div><div class="panel"><div class="panel-head"><h3>Recent activity</h3><a data-go="activity">View log →</a></div><div class="activity-list">${activityRows()}</div></div></div></section>`}
function inventory(){return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">PRODUCT MASTER · PIECES ONLY</div><h2>Inventory</h2></div>${movementActions()}</div><div class="search-bar"><span>⌕</span><input id="inventory-search" placeholder="Search product, category, code or finish..."/><select class="filter-select" id="stock-filter"><option value="all">All stock</option><option value="low">Low stock</option><option value="ok">In stock</option></select></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Product / category / variant</th><th>Available pieces</th><th>Alert threshold</th><th>Status</th></tr></thead><tbody id="inventory-body">${products.length?productRows():`<tr><td colspan="4">${emptyInventory()}</td></tr>`}</tbody></table></div></div></section>`}
function activityView(){return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">AUDIT TRAIL · EVERY MOVEMENT</div><h2>Activity log</h2></div><button class="primary-button" id="add-movement">+ Add movement</button></div><div class="panel"><div class="panel-head"><h3>All stock movements</h3><span class="eyebrow" style="margin:0">${activity.length} entries</span></div><div class="activity-list">${activityRows(activity)}</div></div></section>`}
function reports(){const ins=activity.filter(a=>a.type==='in').reduce((s,a)=>s+a.qty,0), outs=activity.filter(a=>a.type==='out').reduce((s,a)=>s+a.qty,0);return `<section class="main-view"><div class="view-head"><div><div class="eyebrow">INSIGHTS · MOVEMENT SUMMARY</div><h2>Reports</h2></div><button class="primary-button" id="export-report">Export report <span>↓</span></button></div><div class="report-grid"><div class="report-card"><h3>Movement summary</h3><div class="bar-row"><div class="bar-label"><span>Stock received</span><b>${ins.toLocaleString()} pcs</b></div><div class="bar"><i style="width:${Math.min(100,ins/(ins+outs||1)*100)}%"></i></div></div><div class="bar-row"><div class="bar-label"><span>Stock dispatched</span><b>${outs.toLocaleString()} pcs</b></div><div class="bar"><i class="orange" style="width:${Math.min(100,outs/(ins+outs||1)*100)}%"></i></div></div></div><div class="report-card"><h3>Stock health</h3><div class="bar-row"><div class="bar-label"><span>Healthy variants</span><b>${products.length-lowStock().length} / ${products.length}</b></div><div class="bar"><i style="width:${(products.length-lowStock().length)/(products.length||1)*100}%"></i></div></div><div class="bar-row"><div class="bar-label"><span>Needs attention</span><b>${lowStock().length} variants</b></div><div class="bar"><i class="orange" style="width:${lowStock().length/(products.length||1)*100}%"></i></div></div></div><div class="report-card"><h3>Quick actions</h3><button class="primary-button" style="width:100%;margin-bottom:10px" id="report-movement">Record movement →</button><button class="filter-select" style="width:100%;cursor:pointer" id="whatsapp-report">Share summary on WhatsApp ↗</button></div></div></section>`}
function render(){const views={overview,inventory,activity:activityView,reports};$('#view-container').innerHTML=views[currentView]();$('#crumb-view').textContent=currentView.toUpperCase();$('#page-title').innerHTML=currentView==='overview'?'Good morning <span>✦</span>':currentView[0].toUpperCase()+currentView.slice(1);const roleName=currentRole==='admin'?'Owner':'Entry Staff',avatar=currentRole==='admin'?'OW':'ES';$('#user-name').textContent=roleName;$('#user-avatar').textContent=avatar;$('#sidebar-role').textContent=roleName;$('#sidebar-avatar').textContent=avatar;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));document.querySelectorAll('[data-admin-only]').forEach(x=>x.classList.toggle('hidden',currentRole!=='admin'));bindView();}
document.querySelector('#logout-button').addEventListener('click',()=>{sessionStorage.removeItem('godown-role');currentRole=null;document.querySelector('.app-shell').classList.remove('ready');document.querySelector('#login-screen').classList.remove('hidden')});
function openModal(type='in'){const sel=$('#product-select');sel.innerHTML=products.map(p=>`<option value="${p.id}" data-price="${p.price||0}">${p.name} · ${p.variant} · ${money(p.price)}/pc (${p.stock} pcs)</option>`).join('');$('#movement-type').value=type;$('#modal-title').textContent=type==='out'?'Record sale / dispatch':'Add stock movement';$('#movement-price').value=products[0]?.price||'';sel.onchange=()=>{$('#movement-price').value=products.find(p=>p.id===Number(sel.value))?.price||''};$('#modal').classList.remove('hidden');$('#quantity').focus();}
let editingProductId = null;
function openProductModal(product=null){editingProductId=product?.id||null;$('#product-modal-title').textContent=product?'Edit product':'Add your product';$('#product-submit').innerHTML=product?'Save changes <span>→</span>':'Add product <span>→</span>';$('#new-name').value=product?.name||'';$('#new-category').value=product?.category||'';$('#new-code').value=product?.code||'';$('#new-variant').value=product?.variant||'';$('#new-stock').value=product?.stock??'';$('#new-price').value=product?.price ?? '';$('#new-min').value=product?.min??20;$('#product-modal').classList.remove('hidden');$('#new-name').focus()}
function bindView(){const add=$('#add-movement');if(add)add.onclick=openModal;const addPurchase=$('#add-purchase');if(addPurchase)addPurchase.onclick=()=>openModal('in');const addSale=$('#add-sale');if(addSale)addSale.onclick=()=>openModal('out');const addProduct=$('#add-product');if(addProduct){addProduct.onclick=openProductModal;if(currentRole!=='admin')addProduct.classList.add('hidden')}const importButton=$('#import-excel');if(importButton){importButton.onclick=()=>$('#excel-import').click();if(currentRole!=='admin')importButton.classList.add('hidden')}document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{currentView=x.dataset.go;render()});if(currentView==='inventory'){const update=()=>{const term=$('#inventory-search').value.toLowerCase(),filter=$('#stock-filter').value;let list=products.filter(p=>(p.name+p.category+p.code+p.variant).toLowerCase().includes(term)).filter(p=>filter==='all'||(filter==='low'?p.stock<=p.min:p.stock>p.min));$('#inventory-body').innerHTML=productRows(list)};$('#inventory-search').oninput=update;$('#stock-filter').onchange=update}if($('#export-report'))$('#export-report').onclick=exportReport;if($('#whatsapp-report'))$('#whatsapp-report').onclick=shareWhatsApp;if($('#report-movement'))$('#report-movement').onclick=openModal;}
function shareWhatsApp(){const text=`Godown stock summary\nTotal pieces: ${totalStock()}\nVariants: ${products.length}\nLow stock: ${lowStock().length}\nGenerated: ${new Date().toLocaleDateString('en-IN')}`;window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank')}
const normalizeHeader=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const findColumn=(row,names)=>{const aliases={sizevariant:['variant','size','finish','sizevariant'],minimumstock:['minimum','minstock','minimumstock','alert','alertat'],openingstock:['stock','qty','quantity','pieces','closingstock','openingstock'],priceperpiece:['price','rate','unitprice','priceperpiece','mrp','cost']},wanted=new Set(names.flatMap(name=>aliases[normalizeHeader(name)]||[normalizeHeader(name)]));const key=Object.keys(row).find(item=>wanted.has(normalizeHeader(item)));return key?row[key]:''};
document.querySelector('#excel-import').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(!window.XLSX){alert('Excel reader load nahi hua. Internet connection check karke page refresh karo.');return}try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''});let imported=0,skipped=0;rows.forEach(row=>{const name=String(findColumn(row,['product','item','productname','itemname','description'])).trim(),category=String(findColumn(row,['category','group','productcategory'])).trim()||'Uncategorized',code=String(findColumn(row,['code','sku','itemcode','productcode'])).trim()||`IMPORT-${Date.now()}-${imported}`,variant=String(findColumn(row,['variant','size','finish','sizefinish','model'])).trim()||'Standard',stock=Math.max(0,Number(findColumn(row,['stock','qty','quantity','pieces','closingstock','openingstock']))||0),min=Math.max(0,Number(findColumn(row,['minimum','minstock','alert','alertat']))||0);if(!name){skipped++;return}let product=products.find(p=>p.name.toLowerCase()===name.toLowerCase()&&p.category.toLowerCase()===category.toLowerCase()&&p.code.toLowerCase()===code.toLowerCase()&&p.variant.toLowerCase()===variant.toLowerCase());if(product){const before=product.stock;product.stock+=stock;activity.unshift({type:'in',product:product.name,category:product.category,variant:product.variant,qty:stock,beforeStock:before,afterStock:product.stock,stockChange:stock,ref:'Excel import - stock added',time:'Just now'})}else{product={id:Date.now()+imported,name,category,code,variant,stock,min};products.push(product);activity.unshift({type:'in',product:product.name,category:product.category,variant:product.variant,qty:stock,beforeStock:0,afterStock:stock,stockChange:stock,ref:'Excel import - opening stock',time:'Just now'})}imported++});save();render();alert(`${imported} products imported${skipped?`, ${skipped} rows skipped`:''}.`)}catch(error){alert('Excel file read nahi ho saki. Tally export ko .xlsx ya .csv format mein try karo.')}});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()});$('#logout-button').onclick=()=>{sessionStorage.removeItem('godown-role');currentRole=null;$('#login-screen').classList.remove('hidden');document.querySelector('.app-shell').classList.remove('ready')};$('#close-modal').onclick=()=>$('#modal').classList.add('hidden');$('#close-product-modal').onclick=()=>$('#product-modal').classList.add('hidden');document.querySelectorAll('.modal').forEach(modal=>modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')});$('#movement-form').onsubmit=e=>{e.preventDefault();const product=products.find(p=>p.id===Number($('#product-select').value)),type=$('#movement-type').value,qty=Number($('#quantity').value);if(!product)return;if(type==='out'&&qty>product.stock){alert('Available stock se zyada quantity dispatch nahi kar sakte.');return}product.stock+=type==='in'?qty:-qty;activity.unshift({type,product:product.name,variant:product.variant,qty,ref:$('#reference').value||'Manual entry',time:'Just now'});save();$('#modal').classList.add('hidden');e.target.reset();render()};$('#product-form').onsubmit=e=>{e.preventDefault();const name=$('#new-name').value.trim(),category=$('#new-category').value.trim(),code=$('#new-code').value.trim()||`SKU-${Date.now()}`,variant=$('#new-variant').value.trim(),openingStock=Number($('#new-stock').value),min=Number($('#new-min').value),existing=products.find(p=>p.name.toLowerCase()===name.toLowerCase()&&p.category.toLowerCase()===category.toLowerCase()&&p.code.toLowerCase()===code.toLowerCase()&&p.variant.toLowerCase()===variant.toLowerCase());if(existing){existing.stock+=openingStock;existing.min=min;activity.unshift({type:'in',product:existing.name,category:existing.category,variant:existing.variant,qty:openingStock,ref:'Opening stock added to existing product',time:'Just now'})}else{const product={id:Date.now(),name,category,code,variant,stock:openingStock,min};products.push(product);activity.unshift({type:'in',product:product.name,category:product.category,variant:product.variant,qty:product.stock,ref:'Opening stock',time:'Just now'})}save();$('#product-modal').classList.add('hidden');e.target.reset();render()};$('#login-form').onsubmit=e=>{e.preventDefault();const user=$('#login-username').value.trim(),password=$('#login-password').value;if(user==='admin'&&password==='admin123'){currentRole='admin';sessionStorage.setItem('godown-role','admin');$('#login-screen').classList.add('hidden');document.querySelector('.app-shell').classList.add('ready');render()}else $('#login-error').textContent='Username or password is incorrect.'};if(currentRole)$('#login-screen').classList.add('hidden');render();
const selectedProductIds=new Set();
const baseProductRows=productRows;
productRows=list=>{const rows=baseProductRows(list);if(currentView!=='inventory')return rows;let index=0;return rows.replace(/<tr><td class="product-cell">/g,()=>`<tr><td><input type="checkbox" data-select-product="${list[index++]?.id}"></td><td class="product-cell">`)};
const originalInventoryRender=inventory;
inventory=()=>originalInventoryRender().replace('<thead><tr><th>Product / category / variant</th>','<thead><tr><th>Select</th><th>Product / category / variant</th>');
const enhanceBulkDelete=()=>{if(currentView!=='inventory')return;const panel=document.querySelector('.main-view .panel');if(!panel||panel.querySelector('#bulk-delete-bar'))return;const bar=document.createElement('div');bar.id='bulk-delete-bar';bar.className='bulk-bar';bar.innerHTML='<label><input id="select-all-products" type="checkbox"> Select all</label><span id="selected-product-count">0 selected</span><button id="delete-selected-products" type="button" disabled>Delete selected</button>';panel.parentNode.insertBefore(bar,panel);const update=()=>{bar.querySelector('#selected-product-count').textContent=`${selectedProductIds.size} selected`;bar.querySelector('#delete-selected-products').disabled=!selectedProductIds.size;panel.querySelectorAll('[data-select-product]').forEach(input=>input.checked=selectedProductIds.has(Number(input.dataset.selectProduct)))};bar.querySelector('#select-all-products').onchange=event=>{panel.querySelectorAll('[data-select-product]').forEach(input=>{input.checked=event.target.checked;if(event.target.checked)selectedProductIds.add(Number(input.dataset.selectProduct));else selectedProductIds.delete(Number(input.dataset.selectProduct))});update()};panel.addEventListener('change',event=>{if(!event.target.matches('[data-select-product]'))return;if(event.target.checked)selectedProductIds.add(Number(event.target.dataset.selectProduct));else selectedProductIds.delete(Number(event.target.dataset.selectProduct));update()});bar.querySelector('#delete-selected-products').onclick=()=>{const removed=products.filter(product=>selectedProductIds.has(Number(product.id)));products=products.filter(product=>!selectedProductIds.has(Number(product.id)));removed.forEach(product=>activity.unshift({type:'delete',product:product.name,variant:product.variant,qty:product.stock,ref:'Bulk delete',time:'Just now'}));selectedProductIds.clear();save();render()};update()};
const renderWithBulkDelete=render;render=()=>{renderWithBulkDelete();enhanceBulkDelete()};if(currentRole==='admin')render();
